USE commtalk_db_v2;

-- DROP TABLE report;
-- DROP TABLE file;
-- DROP TABLE file_type;
-- DROP TABLE member_activity;
-- DROP TABLE activity_type;
-- DROP TABLE comment;
-- DROP TABLE pinned_board;
-- DROP TABLE post_hashtag;
-- DROP TABLE post;
-- DROP TABLE board;
-- DROP TABLE board_request;
-- DROP TABLE member_password;
-- DROP TABLE member;
-- DROP TABLE member_role;


CREATE TABLE member_role (
    MEMBER_ROLE_ID bigint AUTO_INCREMENT PRIMARY KEY,
    ROLE_NAME varchar(40) NOT NULL,
    CREATED_AT timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT timestamp NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE member (
    MEMBER_ID bigint AUTO_INCREMENT PRIMARY KEY,
    MEMBER_ROLE_ID bigint NOT NULL,
    NICKNAME varchar(255) NOT NULL,
    MEMBER_NAME varchar(40) NOT NULL,
    EMAIL varchar(100) NOT NULL,
    PHONE varchar(100) NOT NULL,
    DELETED_YN tinyint(1) DEFAULT 0,
    CREATED_AT timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (MEMBER_ROLE_ID) REFERENCES member_role(MEMBER_ROLE_ID)
);

CREATE TABLE member_password (
    PASSWORD_ID bigint AUTO_INCREMENT PRIMARY KEY,
    MEMBER_ID bigint NOT NULL,
    PASSWORD varchar(255) NOT NULL,
    CREATED_AT timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (MEMBER_ID) REFERENCES member(MEMBER_ID)
);

CREATE TABLE board (
    BOARD_ID bigint AUTO_INCREMENT PRIMARY KEY,
    MANAGER_ID bigint NOT NULL,
    BOARD_NAME varchar(100) NOT NULL,
    BOARD_DESCRIPTION varchar(255) NULL,
    DELETED_YN tinyint(1) DEFAULT 0,
    CREATED_AT timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (MANAGER_ID) REFERENCES member(MEMBER_ID)
);

CREATE TABLE board_request (
    BOARD_REQ_ID bigint AUTO_INCREMENT PRIMARY KEY,
    BOARD_ID bigint NULL,
    REQUESTER_ID bigint NOT NULL,
    APPROVER_ID bigint NULL,
    BOARD_NAME varchar(100) NOT NULL,
    BOARD_DESCRIPTION varchar(255) NULL,
    REQ_STS int NOT NULL DEFAULT 0, -- 0: 대기, 1: 승인, 2: 거절
    CANCELED_YN tinyint(1) DEFAULT 0,
    CREATED_AT timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (BOARD_ID) REFERENCES board(BOARD_ID),
    FOREIGN KEY (REQUESTER_ID) REFERENCES member(MEMBER_ID),
    FOREIGN KEY (APPROVER_ID) REFERENCES member(MEMBER_ID)
);

CREATE TABLE post (
    POST_ID bigint NOT NULL AUTO_INCREMENT PRIMARY KEY,
    BOARD_ID bigint NOT NULL,
    AUTHOR_ID bigint NOT NULL,
    POST_TITLE varchar(255) NOT NULL,
    POST_CONTENT text NULL,
    ANONYMOUS_YN tinyint(1) DEFAULT 0,
    COMMENTABLE_YN tinyint(1) DEFAULT 0,
    DELETED_YN tinyint(1) DEFAULT 0,
    VIEW_COUNT bigint DEFAULT 0,
    LIKE_COUNT bigint DEFAULT 0,
    SCRAP_COUNT bigint DEFAULT 0,
    CREATED_AT timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (BOARD_ID) REFERENCES board(BOARD_ID),
    FOREIGN KEY (AUTHOR_ID) REFERENCES member(MEMBER_ID)
);

CREATE TABLE post_hashtag (
    HASHTAG_ID bigint AUTO_INCREMENT PRIMARY KEY,
    POST_ID bigint NOT NULL,
    HASHTAG varchar(255) NOT NULL,
    CREATED_AT timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (POST_ID) REFERENCES post(POST_ID)
);

CREATE TABLE pinned_board (
    PINNED_ID bigint AUTO_INCREMENT PRIMARY KEY,
    MEMBER_ID bigint NOT NULL,
    BOARD_ID bigint NOT NULL,
    PINNED_ORDER int NOT NULL,
    CREATED_AT timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (BOARD_ID) REFERENCES board(BOARD_ID),
    FOREIGN KEY (MEMBER_ID) REFERENCES member(MEMBER_ID)
);

CREATE TABLE comment (
    COMMENT_ID bigint AUTO_INCREMENT PRIMARY KEY,
    POST_ID bigint NOT NULL,
    WRITER_ID bigint NOT NULL,
    PARENT_COMMENT_ID bigint NULL,
    COMMENT_CONTENT text NULL,
    ANONYMOUS_YN tinyint(1) DEFAULT 0,
    DELETED_YN tinyint(1) DEFAULT 0,
    LIKE_COUNT bigint DEFAULT 0,
    CREATED_AT timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (POST_ID) REFERENCES post(POST_ID),
    FOREIGN KEY (WRITER_ID) REFERENCES member(MEMBER_ID),
    FOREIGN KEY (PARENT_COMMENT_ID) REFERENCES comment(COMMENT_ID)
);

CREATE TABLE activity_type (
    ACTIVITY_TYPE_ID bigint AUTO_INCREMENT PRIMARY KEY,
    TYPE_NAME varchar(40) NOT NULL,
    CREATED_AT timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT timestamp NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE member_activity (
    ACTIVITY_ID bigint AUTO_INCREMENT PRIMARY KEY,
    ACTIVITY_TYPE_ID bigint NOT NULL,
    MEMBER_ID bigint NOT NULL,
    REF_ID bigint NOT NULL,
    CREATED_AT timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ACTIVITY_TYPE_ID) REFERENCES activity_type(ACTIVITY_TYPE_ID),
    FOREIGN KEY (MEMBER_ID) REFERENCES member(MEMBER_ID)
);

CREATE TABLE file_type (
    FILE_TYPE_ID bigint AUTO_INCREMENT PRIMARY KEY,
    TYPE_NAME varchar(40) NOT NULL,
    CREATED_AT timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT timestamp NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE file (
    FILE_ID bigint AUTO_INCREMENT PRIMARY KEY,
    FILE_TYPE_ID bigint NOT NULL,
    REF_ID bigint NOT NULL,
    FILE_PATH varchar(255) NOT NULL,
    ORIGINAL_FILE_NAME varchar(255) NOT NULL,
    SAVE_FILE_NAME varchar(255) NOT NULL,
    FILE_EXT varchar(10) NOT NULL,
    FILE_SIZE bigint NULL,
    DELETED_YN tinyint(1) DEFAULT 0,
    CREATED_AT timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (FILE_TYPE_ID) REFERENCES file_type(FILE_TYPE_ID)
);

CREATE TABLE report (
    REPORT_ID bigint AUTO_INCREMENT PRIMARY KEY,
    REPORTER_ID bigint NOT NULL,
    MANAGER_ID bigint NOT NULL,
    POST_ID bigint NOT NULL,
    COMMENT_ID bigint NULL,
    REPORT_REASON text NOT NULL,
    REPORT_STATUS enum('PENDING','PROCESSED', 'REJECTED') NULL,
    ACTION_TAKEN enum('DELETE','WARN','LIMIT') NULL,
    ACTIONED_AT timestamp NULL,
    CREATED_AT timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (REPORTER_ID) REFERENCES member(MEMBER_ID),
    FOREIGN KEY (MANAGER_ID) REFERENCES member(MEMBER_ID),
    FOREIGN KEY (POST_ID) REFERENCES post(POST_ID),
    FOREIGN KEY (COMMENT_ID) REFERENCES comment(COMMENT_ID)
);

CREATE USER 'commtalk'@'localhost' IDENTIFIED BY 'commtalk';
GRANT ALL PRIVILEGES ON commtalk_db_v2.* TO 'commtalk'@'localhost';
FLUSH PRIVILEGES;

commit;